# Generated by Django 4.1.2 on 2022-11-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectowebapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
